INSERT INTO exercise (id, name, muscle, equipment, description) VALUES
(1, 'Barbell bench press', 'Chest', 'Barbell', 'A horizontal press. Log the total barbell load in kilograms.'),
(2, 'Incline dumbbell press', 'Chest', 'Dumbbell', 'An incline press. Log the combined weight of both dumbbells.'),
(3, 'Cable fly', 'Chest', 'Cable', 'A cable chest movement. Use the same load convention each session.'),
(4, 'Push-up', 'Chest', 'Bodyweight', 'A bodyweight press. Log only added external load; use 0 kg when unweighted.'),
(5, 'Lat pulldown', 'Back', 'Cable', 'A vertical pull. Record the selected machine load.'),
(6, 'Barbell row', 'Back', 'Barbell', 'A horizontal pull. Record the total barbell load.'),
(7, 'Seated cable row', 'Back', 'Cable', 'A seated horizontal pull. Record the selected machine load.'),
(8, 'Pull-up', 'Back', 'Bodyweight', 'A bodyweight vertical pull. Log added load only; use 0 kg when unweighted.'),
(9, 'Back squat', 'Legs', 'Barbell', 'A barbell squat. Record the total load including the bar.'),
(10, 'Romanian deadlift', 'Legs', 'Barbell', 'A hip hinge movement. Record the total barbell load.'),
(11, 'Leg press', 'Legs', 'Machine', 'A machine leg press. Keep the machine and load convention consistent.'),
(12, 'Leg curl', 'Legs', 'Machine', 'A knee flexion movement. Record the selected machine load.'),
(13, 'Walking lunge', 'Legs', 'Dumbbell', 'Log total repetitions across both legs and the combined dumbbell load.'),
(14, 'Calf raise', 'Legs', 'Machine', 'Log the machine or added external load.'),
(15, 'Overhead press', 'Shoulders', 'Barbell', 'A vertical press. Record the total barbell load.'),
(16, 'Lateral raise', 'Shoulders', 'Dumbbell', 'Log the combined weight of both dumbbells.'),
(17, 'Face pull', 'Shoulders', 'Cable', 'A cable upper-back movement. Record the selected machine load.'),
(18, 'Dumbbell curl', 'Arms', 'Dumbbell', 'Log repetitions per arm and the combined weight of both dumbbells.'),
(19, 'Triceps pushdown', 'Arms', 'Cable', 'A cable arm movement. Record the selected machine load.'),
(20, 'Hammer curl', 'Arms', 'Dumbbell', 'Log repetitions per arm and the combined weight of both dumbbells.'),
(21, 'Deadlift', 'Full body', 'Barbell', 'A barbell pull from the floor. Record total barbell load.'),
(22, 'Goblet squat', 'Legs', 'Dumbbell', 'Log the weight of the single dumbbell or kettlebell.'),
(23, 'Cable crunch', 'Core', 'Cable', 'A loaded trunk movement. Record the selected machine load.'),
(24, 'Hanging knee raise', 'Core', 'Bodyweight', 'Record completed repetitions and any external load, or 0 kg.');
